---
title: "Sufganiyot Recipe"
format: pdf
---

Taken from [The Taste of Kosher](https://www.thetasteofkosher.com/sufganiyot-recipe/).

Sufganiyot are the most popular Chanukah food in Israel and are found everywhere for at least a month or two prior to the holiday.

Prep Time: 10 minutes
Cook Time: 15 minutes
Additional Time: 2 hours
Total Time: 2 hours 25 minutes

# Ingredients

* 4 cups all-purpose flour (500 grams)
* 1/2 cup white sugar (100 grams)
* 1 tablespoon dry yeast
* 1 teaspoon salt
* 1/4 cup oil (60 milliliters) and extra for frying
* 2 eggs
* 3/4 cup warm water (175 milliliters)
* 1 tablespoon vanilla extract*

# Filling and Dusting

* 1 cup strawberry jelly (300 grams)
* 1/4 cup powdered sugar (30 grams)

# Instructions

* Place flour, sugar, yeast, and salt into the bowl of the stand mixer. Mix.
* Add oil, eggs, water, and vanilla extract. Knead using a bread hook. Leave the dough to mix on low for 10 minutes, at the end of which it should be smooth but tacky. Add more flour if needed.
* Move the dough to an oiled bowl. Cover with a towel or plastic wrap and let sit until double in size.
* Place the dough on a well floured surface and sprinkle the top with flour as well. Roll the dough out until it is about 1/2 inch or 1.25 cm. Cut out circles using a 2'' or 3'' cookie cutter dipped in flour.
* Using a spatula, carefully remove the circles and place them on a floured tray. Take the remaining scraps and knead them together. Let sit for 5 minutes.  
* Repeat steps 4 and 5 until dough is used up. Sprinkle the circles with flour and cover with a towel. Set aside and let sit for 40 minutes in a warm place.
* Fill a large pot with oil for frying, 2 inches deep (5 centimeters).
* Heat the oil to 320F - 340F or 160C - 170C. If you do not have a thermometer, test the oil by placing a small piece of dough in it. If it sizzles and floats, the oil is hot enough.
* Place 3 or 4 sufganiyot in the pot one at a time. Do not crowd. Let them simmer for 1 ½ minutes on each side until golden brown. Remove and set aside.
* Using a squeeze bottle or a syringe filled with jelly, puncture a hole in the top and fill. Dust with sugar.

# Notes

* Vanilla extract isn't cheap. Instead, you can use one teaspoon of extract and 1 tablespoon of liquor.

# Nutrition Information

Yield: 16
Serving Size: 1

# Amount Per Serving

Calories: 227T
otal Fat: 4g
Saturated Fat: 0g
Trans Fat: 0g
Unsaturated Fat: 4g
Cholesterol: 23mg
Sodium: 147mg
Carbohydrates: 42g
Fiber: 1g
Sugar: 15g
Protein: 4g	
